@Mdm.API_HostAddress = http://localhost:5074

POST {{Mdm.API_HostAddress}}/CreateElementType/
Accept: application/json
Content-Type: application/json

{
  "name": "VendorService"
}
###

POST {{Mdm.API_HostAddress}}/CreateElement/
Accept: application/json
Content-Type: application/json

{
  "name": "VendorService"
}
###

POST {{Mdm.API_HostAddress}}/FilterElements/
Accept: application/json
Content-Type: application/json

{
}
###
